version: "3.9"  # optional since v1.27.0
services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    links: 
      - db
    depends_on: 
      - db
    environment: 
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres
    volumes:
      - ./src:/usr/src/app/src
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - api-db:/var/lib/postgresql/data
volumes:
  api-db: {}
