name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
        with:
          access_key: ${{ secret.AWS_ACCESS_KEY }}
          secret_key: ${{ secret.AWS_SECRET_KEY }}
          bucket: ${{ secret.AWS_S3_BUCKET }}
          key: ${{ secret.AWS_S3_KEY }}
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color