name: CI/CD
on:
  push:
    branches:
      - master
jobs:
  integration:
    name: CI
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint code
        run: npx eslint .

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      # - name: Terraform Format
      #   id: fmt
      #   run: terraform fmt -check
      # - name: Terraform Init
      #   id: init
      #   run: terraform init -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY }}" -backend-config="bucket=${{ secrets.AWS_S3_BUCKET }}" -backend-config="key=${{ secrets.AWS_S3_KEY }}"
      # - name: Terraform Validate
      #   id: validate
      #   run: terraform validate -no-color
      